
export const FETCH_REQUEST_FETCHING = 'FETCH_REQUEST_FETCHING'
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'

export const SET_ERRORS = 'SET_ERRORS'

export const ADD_WATCHED_NOTIFICATIONS = 'ADD_WATCHED_NOTIFICATIONS'

export const SET_SETTINGS = 'SET_SETTINGS'
export const RESET_SETTINGS = 'RESET_SETTINGS'

export const SET_USERDATA = 'SET_USERDATA'
export const UNSET_USERDATA = 'UNSET_USERDATA'

export const UPDATE_NOTIFICATIONSEENDATE = 'UPDATE_NOTIFICATIONSEENDATE'

export const ADD_SAVED_MESSAGE = 'ADD_SAVED_MESSAGE'

export const SET_PUSH_IDS_LOCAL = 'SET_PUSH_IDS_LOCAL'
export const SET_PUSH_NOTIF_DATA = 'SET_PUSH_NOTIF_DATA'

export const FETCH_USER_FETCHING = 'FETCH_USER_FETCHING'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'

export const FETCH_COUNTRYCODES_FETCHING = 'FETCH_COUNTRYCODES_FETCHING'
export const FETCH_COUNTRYCODES_ERROR = 'FETCH_COUNTRYCODES_ERROR'
export const FETCH_COUNTRYCODES_SUCCESS = 'FETCH_COUNTRYCODES_SUCCESS'

export const SET_CONTACTS = 'SET_CONTACTS'
export const SET_PERMANENT_CONTACTS = 'SET_PERMANENT_CONTACTS'
export const SET_FRESH_CONTACTS = 'SET_FRESH_CONTACTS'

export const UNSET_CONTACTS = 'UNSET_CONTACTS'

export const SET_MAKEINTRODUCTIONDATA = 'SET_MAKEINTRODUCTIONDATA'
export const UNSET_MAKEINTRODUCTIONDATA = 'UNSET_MAKEINTRODUCTIONDATA'

export const SET_PHONEINDEX = 'SET_PHONEINDEX'
export const RESET_PHONEINDEX = 'RESET_PHONEINDEX'

export const FETCH_CREATEUSER_FETCHING = 'FETCH_CREATEUSER_FETCHING'
export const FETCH_CREATEUSER_ERROR = 'FETCH_CREATEUSER_ERROR'
export const FETCH_CREATEUSER_SUCCESS = 'FETCH_CREATEUSER_SUCCESS'

export const FETCH_VALIDATETOKEN_FETCHING = 'FETCH_VALIDATETOKEN_FETCHING'
export const FETCH_VALIDATETOKEN_ERROR = 'FETCH_VALIDATETOKEN_ERROR'
export const FETCH_VALIDATETOKEN_SUCCESS = 'FETCH_VALIDATETOKEN_SUCCESS'

export const FETCH_AUTHENTICATE_FETCHING = 'FETCH_AUTHENTICATE_FETCHING'
export const FETCH_AUTHENTICATE_ERROR = 'FETCH_AUTHENTICATE_ERROR'
export const FETCH_AUTHENTICATE_SUCCESS = 'FETCH_AUTHENTICATE_SUCCESS'

export const FETCH_RESETPSWDREQUEST_FETCHING = 'FETCH_RESETPSWDREQUEST_FETCHING'
export const FETCH_RESETPSWDREQUEST_ERROR = 'FETCH_RESETPSWDREQUEST_ERROR'
export const FETCH_RESETPSWDREQUEST_SUCCESS = 'FETCH_RESETPSWDREQUEST_SUCCESS'

export const FETCH_PARSETOKEN_FETCHING = 'FETCH_PARSETOKEN_FETCHING'
export const FETCH_PARSETOKEN_ERROR = 'FETCH_PARSETOKEN_ERROR'
export const FETCH_PARSETOKEN_SUCCESS = 'FETCH_PARSETOKEN_SUCCESS'

export const FETCH_GETUSERS_FETCHING = 'FETCH_GETUSERS_FETCHING'
export const FETCH_GETUSERS_ERROR = 'FETCH_GETUSERS_ERROR'
export const FETCH_GETUSERS_SUCCESS = 'FETCH_GETUSERS_SUCCESS'

export const FETCH_GETALLUSERS_FETCHING = 'FETCH_GETALLUSERS_FETCHING'
export const FETCH_GETALLUSERS_ERROR = 'FETCH_GETALLUSERS_ERROR'
export const FETCH_GETALLUSERS_SUCCESS = 'FETCH_GETALLUSERS_SUCCESS'

export const FETCH_DELETEUSER_FETCHING = 'FETCH_DELETEUSER_FETCHING'
export const FETCH_DELETEUSER_ERROR = 'FETCH_DELETEUSER_ERROR'
export const FETCH_DELETEUSER_SUCCESS = 'FETCH_DELETEUSER_SUCCESS'

export const FETCH_UPDATEUSER_FETCHING = 'FETCH_UPDATEUSER_FETCHING'
export const FETCH_UPDATEUSER_ERROR = 'FETCH_UPDATEUSER_ERROR'
export const FETCH_UPDATEUSER_SUCCESS = 'FETCH_UPDATEUSER_SUCCESS'

export const FETCH_SETNEWPSWDREQUEST_FETCHING = 'FETCH_SETNEWPSWDREQUEST_FETCHING'
export const FETCH_SETNEWPSWDREQUEST_ERROR = 'FETCH_SETNEWPSWDREQUEST_ERROR'
export const FETCH_SETNEWPSWDREQUEST_SUCCESS = 'FETCH_SETNEWPSWDREQUEST_SUCCESS'

export const FETCH_SENDSMS_FETCHING = 'FETCH_SENDSMS_FETCHING'
export const FETCH_SENDSMS_ERROR = 'FETCH_SENDSMS_ERROR'
export const FETCH_SENDSMS_SUCCESS = 'FETCH_SENDSMS_SUCCESS'

export const FETCH_UPLOADIMAGE_FETCHING = 'FETCH_UPLOADIMAGE_FETCHING'
export const FETCH_UPLOADIMAGE_ERROR = 'FETCH_UPLOADIMAGE_ERROR'
export const FETCH_UPLOADIMAGE_SUCCESS = 'FETCH_UPLOADIMAGE_SUCCESS'

export const FETCH_GETIMAGE_FETCHING = 'FETCH_GETIMAGE_FETCHING'
export const FETCH_GETIMAGE_ERROR = 'FETCH_GETIMAGE_ERROR'
export const FETCH_GETIMAGE_SUCCESS = 'FETCH_GETIMAGE_SUCCESS'

export const FETCH_KVSUPDATERECORD_FETCHING = 'FETCH_KVSUPDATERECORD_FETCHING'
export const FETCH_KVSUPDATERECORD_ERROR = 'FETCH_KVSUPDATERECORD_ERROR'
export const FETCH_KVSUPDATERECORD_SUCCESS = 'FETCH_KVSUPDATERECORD_SUCCESS'

export const FETCH_KVSREADRECORD_FETCHING = 'FETCH_KVSREADRECORD_FETCHING'
export const FETCH_KVSREADRECORD_ERROR = 'FETCH_KVSREADRECORD_ERROR'
export const FETCH_KVSREADRECORD_SUCCESS = 'FETCH_KVSREADRECORD_SUCCESS'

export const FETCH_KVSCREATERECORD_FETCHING = 'FETCH_KVSCREATERECORD_FETCHING'
export const FETCH_KVSCREATERECORD_ERROR = 'FETCH_KVSCREATERECORD_ERROR'
export const FETCH_KVSCREATERECORD_SUCCESS = 'FETCH_KVSCREATERECORD_SUCCESS'

export const FETCH_KVSDELETERECORD_FETCHING = 'FETCH_KVSDELETERECORD_FETCHING'
export const FETCH_KVSDELETERECORD_ERROR = 'FETCH_KVSDELETERECORD_ERROR'
export const FETCH_KVSDELETERECORD_SUCCESS = 'FETCH_KVSDELETERECORD_SUCCESS'

// models actionTypes
export const FETCH_SETSETTINGS_FETCHING = 'FETCH_SETSETTINGS_FETCHING'
export const FETCH_SETSETTINGS_ERROR = 'FETCH_SETSETTINGS_ERROR'
export const FETCH_SETSETTINGS_SUCCESS = 'FETCH_SETSETTINGS_SUCCESS'

export const FETCH_UPDATESETTINGS_FETCHING = 'FETCH_UPDATESETTINGS_FETCHING'
export const FETCH_UPDATESETTINGS_ERROR = 'FETCH_UPDATESETTINGS_ERROR'
export const FETCH_UPDATESETTINGS_SUCCESS = 'FETCH_UPDATESETTINGS_SUCCESS'

export const FETCH_GETSETTINGS_FETCHING = 'FETCH_GETSETTINGS_FETCHING'
export const FETCH_GETSETTINGS_ERROR = 'FETCH_GETSETTINGS_ERROR'
export const FETCH_GETSETTINGS_SUCCESS = 'FETCH_GETSETTINGS_SUCCESS'

export const FETCH_MAKEINTRODUCTION_FETCHING = 'FETCH_MAKEINTRODUCTION_FETCHING'
export const FETCH_MAKEINTRODUCTION_ERROR = 'FETCH_MAKEINTRODUCTION_ERROR'
export const FETCH_MAKEINTRODUCTION_SUCCESS = 'FETCH_MAKEINTRODUCTION_SUCCESS'

export const FETCH_UPDATEINTRODUCTION_FETCHING = 'FETCH_UPDATEINTRODUCTION_FETCHING'
export const FETCH_UPDATEINTRODUCTION_ERROR = 'FETCH_UPDATEINTRODUCTION_ERROR'
export const FETCH_UPDATEINTRODUCTION_SUCCESS = 'FETCH_UPDATEINTRODUCTION_SUCCESS'

export const FETCH_HIDECONNECTION_FETCHING = 'FETCH_HIDECONNECTION_FETCHING'
export const FETCH_HIDECONNECTION_ERROR = 'FETCH_HIDECONNECTION_ERROR'
export const FETCH_HIDECONNECTION_SUCCESS = 'FETCH_HIDECONNECTION_SUCCESS'

export const FETCH_GETINTRODUCTIONBYID_FETCHING = 'FETCH_GETINTRODUCTIONBYID_FETCHING'
export const FETCH_GETINTRODUCTIONBYID_ERROR = 'FETCH_GETINTRODUCTIONBYID_ERROR'
export const FETCH_GETINTRODUCTIONBYID_SUCCESS = 'FETCH_GETINTRODUCTIONBYID_SUCCESS'

export const FETCH_DELETEINTRODUCTION_FETCHING = 'FETCH_DELETEINTRODUCTION_FETCHING'
export const FETCH_DELETEINTRODUCTION_ERROR = 'FETCH_DELETEINTRODUCTION_ERROR'
export const FETCH_DELETEINTRODUCTION_SUCCESS = 'FETCH_DELETEINTRODUCTION_SUCCESS'

export const FETCH_GETMYINTRODUCTIONS_FETCHING = 'FETCH_GETMYINTRODUCTIONS_FETCHING'
export const FETCH_GETMYINTRODUCTIONS_ERROR = 'FETCH_GETMYINTRODUCTIONS_ERROR'
export const FETCH_GETMYINTRODUCTIONS_SUCCESS = 'FETCH_GETMYINTRODUCTIONS_SUCCESS'

export const FETCH_GETMYCONNECTIONS_FETCHING = 'FETCH_GETMYCONNECTIONS_FETCHING'
export const FETCH_GETMYCONNECTIONS_ERROR = 'FETCH_GETMYCONNECTIONS_ERROR'
export const FETCH_GETMYCONNECTIONS_SUCCESS = 'FETCH_GETMYCONNECTIONS_SUCCESS'

export const FETCH_ADDNOTIFICATION_FETCHING = 'FETCH_ADDNOTIFICATION_FETCHING'
export const FETCH_ADDNOTIFICATION_ERROR = 'FETCH_ADDNOTIFICATION_ERROR'
export const FETCH_ADDNOTIFICATION_SUCCESS = 'FETCH_ADDNOTIFICATION_SUCCESS'

export const FETCH_UPDATENOTIFICATIONS_FETCHING = 'FETCH_UPDATENOTIFICATIONS_FETCHING'
export const FETCH_UPDATENOTIFICATIONS_ERROR = 'FETCH_UPDATENOTIFICATIONS_ERROR'
export const FETCH_UPDATENOTIFICATIONS_SUCCESS = 'FETCH_UPDATENOTIFICATIONS_SUCCESS'

export const FETCH_GETNOTIFICATIONS_FETCHING = 'FETCH_GETNOTIFICATIONS_FETCHING'
export const FETCH_GETNOTIFICATIONS_ERROR = 'FETCH_GETNOTIFICATIONS_ERROR'
export const FETCH_GETNOTIFICATIONS_SUCCESS = 'FETCH_GETNOTIFICATIONS_SUCCESS'

export const FETCH_GETNOTIFICATIONBYID_FETCHING = 'FETCH_GETNOTIFICATIONBYID_FETCHING'
export const FETCH_GETNOTIFICATIONBYID_ERROR = 'FETCH_GETNOTIFICATIONBYID_ERROR'
export const FETCH_GETNOTIFICATIONBYID_SUCCESS = 'FETCH_GETNOTIFICATIONBYID_SUCCESS'

export const FETCH_GETUSERPUSHIDS_FETCHING = 'FETCH_GETUSERPUSHIDS_FETCHING'
export const FETCH_GETUSERPUSHIDS_ERROR = 'FETCH_GETUSERPUSHIDS_ERROR'
export const FETCH_GETUSERPUSHIDS_SUCCESS = 'FETCH_GETUSERPUSHIDS_SUCCESS'

export const FETCH_SETUSERPUSHIDS_FETCHING = 'FETCH_SETUSERPUSHIDS_FETCHING'
export const FETCH_SETUSERPUSHIDS_ERROR = 'FETCH_SETUSERPUSHIDS_ERROR'
export const FETCH_SETUSERPUSHIDS_SUCCESS = 'FETCH_SETUSERPUSHIDS_SUCCESS'

export const FETCH_GETUSERSPUSHID_FETCHING = 'FETCH_GETUSERSPUSHID_FETCHING'
export const FETCH_GETUSERSPUSHID_ERROR = 'FETCH_GETUSERSPUSHID_ERROR'
export const FETCH_GETUSERSPUSHID_SUCCESS = 'FETCH_GETUSERSPUSHID_SUCCESS'

export const FETCH_GETUSERSPUSHIDS_FETCHING = 'FETCH_GETUSERSPUSHIDS_FETCHING'
export const FETCH_GETUSERSPUSHIDS_ERROR = 'FETCH_GETUSERSPUSHIDS_ERROR'
export const FETCH_GETUSERSPUSHIDS_SUCCESS = 'FETCH_GETUSERSPUSHIDS_SUCCESS'

export const FETCH_INVITEUSER_FETCHING = 'FETCH_INVITEUSER_FETCHING'
export const FETCH_INVITEUSER_ERROR = 'FETCH_INVITEUSER_ERROR'
export const FETCH_INVITEUSER_SUCCESS = 'FETCH_INVITEUSER_SUCCESS'

export const FETCH_INVITEFRIEND_FETCHING = 'FETCH_INVITEFRIEND_FETCHING'
export const FETCH_INVITEFRIEND_ERROR = 'FETCH_INVITEUSER_ERROR'
export const FETCH_INVITEFRIEND_SUCCESS = 'FETCH_INVITEUSER_SUCCESS'

export const FETCH_GETUSERSSETTINGS_FETCHING = 'FETCH_GETUSERSSETTINGS_FETCHING'
export const FETCH_GETUSERSSETTINGS_ERROR = 'FETCH_GETUSERSSETTINGS_ERROR'
export const FETCH_GETUSERSSETTINGS_SUCCESS = 'FETCH_GETUSERSSETTINGS_SUCCESS'

export const FETCH_CONNECT_FETCHING = 'FETCH_CONNECT_FETCHING'
export const FETCH_CONNECT_ERROR = 'FETCH_CONNECT_ERROR'
export const FETCH_CONNECT_SUCCESS = 'FETCH_CONNECT_SUCCESS'

export const FETCH_UPDATEPUSHIDS_FETCHING = 'FETCH_UPDATEPUSHIDS_FETCHING'
export const FETCH_UPDATEPUSHIDS_ERROR = 'FETCH_UPDATEPUSHIDS_ERROR'
export const FETCH_UPDATEPUSHIDS_SUCCESS = 'FETCH_UPDATEPUSHIDS_SUCCESS'

export const FETCH_SETCUSTOMMESSAGES_FETCHING = 'FETCH_SETCUSTOMMESSAGES_FETCHING'
export const FETCH_SETCUSTOMMESSAGES_ERROR = 'FETCH_SETCUSTOMMESSAGES_ERROR'
export const FETCH_SETCUSTOMMESSAGES_SUCCESS = 'FETCH_SETCUSTOMMESSAGES_SUCCESS'

export const FETCH_GETUSERCUSTOMMESSAGES_FETCHING = 'FETCH_GETUSERCUSTOMMESSAGES_FETCHING'
export const FETCH_GETUSERCUSTOMMESSAGES_ERROR = 'FETCH_GETUSERCUSTOMMESSAGES_ERROR'
export const FETCH_GETUSERCUSTOMMESSAGES_SUCCESS = 'FETCH_GETUSERCUSTOMMESSAGES_SUCCESS'

export const FETCH_GETUSERSCUSTOMMESSAGES_FETCHING = 'FETCH_GETUSERSCUSTOMMESSAGES_FETCHING'
export const FETCH_GETUSERSCUSTOMMESSAGES_ERROR = 'FETCH_GETUSERSCUSTOMMESSAGES_ERROR'
export const FETCH_GETUSERSCUSTOMMESSAGES_SUCCESS = 'FETCH_GETUSERSCUSTOMMESSAGES_SUCCESS'

export const FETCH_UPDATECUSTOMMESSAGES_FETCHING = 'FETCH_UPDATECUSTOMMESSAGES_FETCHING'
export const FETCH_UPDATECUSTOMMESSAGES_ERROR = 'FETCH_UPDATECUSTOMMESSAGES_ERROR'
export const FETCH_UPDATECUSTOMMESSAGES_SUCCESS = 'FETCH_UPDATECUSTOMMESSAGES_SUCCESS'

export const FETCH_LOGGER_FETCHING = 'FETCH_LOGGER_FETCHING'
export const FETCH_LOGGER_ERROR = 'FETCH_LOGGER_ERROR'
export const FETCH_LOGGER_SUCCESS = 'FETCH_LOGGER_SUCCESS'

export const FETCH_CONTACTSEXIST_FETCHING = 'FETCH_CONTACTSEXIST_FETCHING'
export const FETCH_CONTACTSEXIST_ERROR = 'FETCH_CONTACTSEXIST_ERROR'
export const FETCH_CONTACTSEXIST_SUCCESS = 'FETCH_CONTACTSEXIST_SUCCESS'

export const FETCH_REMOTECONTACTS_FETCHING = 'FETCH_REMOTECONTACTS_FETCHING'
export const FETCH_REMOTECONTACTS_ERROR = 'FETCH_REMOTECONTACTS_ERROR'
export const FETCH_REMOTECONTACTS_SUCCESS = 'FETCH_REMOTECONTACTS_SUCCESS'
